name: example
description: Reactive Grid Example
version: 2.0.0
publish_to: "none"

environment:
  sdk: ^3.13.0
  flutter: ">=3.38.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bootstrap_grid:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
