name: bootstrap_grid
description: Bootstrap Grid Implementation
version: 1.0.5
homepage: https://github.com/4D-Technologies/bootstrap_grid

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
